#ifndef REPORT_GENERATE_GLOBAL_H
#define REPORT_GENERATE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REPORT_GENERATE_LIBRARY)
#  define REPORT_GENERATE_EXPORT Q_DECL_EXPORT
#else
#  define REPORT_GENERATE_EXPORT Q_DECL_IMPORT
#endif

#endif // REPORT_GENERATE_GLOBAL_H
